twitterautoreplybot/main/urls.py
from django.conf.urls import url

from main.views import IndexView, CampaignCreate, CampaignUpdate, CampaignView, CampaignSchedule, CampaignUnschedule

urlpatterns = [
    url(r'^$', IndexView, name='IndexView'),
    url(r'^campaign/new/$', CampaignCreate.as_view(), name='CampaignCreate'),
    url(r'^campaign/(?P<pk>[0-9]+)/edit$', CampaignUpdate.as_view(), name='CampaignUpdate'),
    url(r'^campaign/(?P<pk>[0-9]+)/$', CampaignView.as_view(), name='CampaignView'),
    url(r'^campaign/(?P<pk>[0-9]+)/schedule/$', CampaignSchedule, name='CampaignSchedule'),
    url(r'^campaign/(?P<pk>[0-9]+)/unschedule/$', CampaignUnschedule, name='CampaignUnschedule')
]

twitterautoreplybot/twitterautoreplybot/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('main.urls', namespace="main")),
    url('^', include('django.contrib.auth.urls')),
    url(r'^django-rq/', include('django_rq.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

twitterautoreplybot/main/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from main.extras import Bitly

import re, random, twitter

# Create your models here.        
class Campaign(models.Model):
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="campaigns", blank=True, null=True, editable=False)
    name = models.CharField(max_length=255)
    answerSentence = models.TextField()
    running = models.BooleanField(default=False)
    lastRun = models.DateTimeField(blank=True, null=True, editable=False)
    jobId = models.CharField(max_length=255, blank=True, null=True, editable=False)
    
    def nbTweetsReplied(self):
        return self.tweet_actions.filter(action__type__exact="replied").count()
    def nbTweetsClicked(self):
        return self.tweet_actions.filter(clicked=True).count()
        
    def getTweetDetails(self, limit=5):
        tweetActions = self.tweet_actions.filter(action__type__exact="replied").order_by('-pk')[:limit]
        tweetDetails = []
        
        twitterClient = twitter.Api(
            consumer_key = settings.TWITTER_CONSUMER_KEY,
            consumer_secret = settings.TWITTER_CONSUMER_SECRET,
            access_token_key = settings.TWITTER_ACCESS_TOKEN,
            access_token_secret = settings.TWITTER_ACCESS_SECRET
        )
        for tweetAction in tweetActions:
            try:
                tweet = twitterClient.GetStatus(id = tweetAction.tweet.tweet_id, include_entities = True)
                tweetDetails.append({"id": tweet.id, "message": tweet.text, "query": tweetAction.query, "clicked": tweetAction.clicked})
            except twitter.TwitterError:
                tweetDetails.append({"id": tweet.id, "message": "-", "query": tweetAction.query, "clicked": tweetAction.clicked})
        
        return tweetDetails
    
    def generateAnswerSentence(self, twitterUsername, tweetId, queryMagicWord):
        toReturn = self.answerSentence
        # Replace Twitter username, tweet id, and magic word
        toReturn = toReturn.replace('%twitterUsername%', twitterUsername)
        toReturn = toReturn.replace('%tweetId%', tweetId)
        toReturn = toReturn.replace('%magicWord%', queryMagicWord)
        
        # Shorten URLs
        urls = re.findall(r'(https?://\S+)', toReturn)
        shortenedUrls = []
        if (len(urls) > 0):
            bitly = Bitly.Bitly()
            shortenedUrls = bitly.shorten_urls(urls)
            for index, url in enumerate(urls):
                toReturn = toReturn.replace(url, shortenedUrls[index])
        
        # Process word sets
        p = re.compile(ur'\[([^\]]+)\]')
        wordSets = re.findall(p, toReturn)
        for wordSet in wordSets:
            words = wordSet.split('|')
            randomWord = random.choice(words)
            toReturn = toReturn.replace("[" + wordSet + "]", randomWord, 1)
            
        return toReturn, shortenedUrls
    
    def __unicode__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('main:CampaignView', kwargs={'pk': self.pk})
        
class Query(models.Model):
    query = models.CharField(max_length=255)
    correspondingSentence = models.CharField(max_length=255)
    campaign = models.ForeignKey(Campaign, related_name="queries")
    requiredNumberOfImages = models.IntegerField(blank=True, null=True)
    
    def nbTweetsSeen(self):
        return Tweet.objects.filter(tweet_actions__query__pk__exact=self.pk).count()
    def nbTweetsReplied(self):
        return Tweet.objects.filter(tweet_actions__query__pk__exact=self.pk, tweet_actions__action__type__exact="replied").count()
    def nbTweetsClicked(self):
        return Tweet.objects.filter(tweet_actions__query__pk__exact=self.pk, tweet_actions__clicked=True).count()
    
    def __unicode__(self):
        return self.query
    
class Action(models.Model):
    type = models.CharField(max_length=255)
    
    def __unicode__(self):
        return self.type   
    
class Tweet(models.Model):
    tweet_id = models.CharField(max_length=255)
    
    def __unicode__(self):
        return self.tweet_id
        
class TweetAction(models.Model):
    tweet = models.ForeignKey(Tweet, related_name="tweet_actions")
    action = models.ForeignKey(Action)
    query = models.ForeignKey(Query, related_name="tweet_actions")
    campaign = models.ForeignKey(Campaign, related_name="tweet_actions")
    shortened_urls = models.TextField(blank=True, null=True)
    clicked = models.BooleanField(default=False)
    
    def setShortenedUrls(self, shortenedUrls):
        self.shortened_urls = ','.join(shortenedUrls)
        
    def getShortenedUrls(self):
        return self.shortened_urls.split(",")

class Image(models.Model):
    tweet = models.ForeignKey(Tweet, related_name="images")
    url = models.URLField()
    
    def __unicode__(self):
        return self.url

twitterautoreplybot/main/forms.py
from django.forms import ModelForm
from extra_views import InlineFormSet

from .models import Campaign, Query

class CampaignForm(ModelForm):
    class Meta:
        model = Campaign
        fields = ["name", "answerSentence"]
        exclude = ["creator"]
    
class QueryFormSet(InlineFormSet):
    model = Query
    extra = 1
    
class QueryFormSetUpdate(InlineFormSet):
    model = Query
    extra = 0

twitterautoreplybot/main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import DetailView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponseForbidden, JsonResponse
from django.conf import settings
from django.forms.formsets import all_valid
from extra_views import CreateWithInlinesView, UpdateWithInlinesView

import django, django_rq, datetime, sys, bitly_api

from .models import Tweet, Campaign, TweetAction
from .forms import CampaignForm, QueryFormSet, QueryFormSetUpdate
from .extras import TwitterBot
import main

# Custom mixin to check ownership
def campaign_owner(func):
    def check_and_call(request, *args, **kwargs):
        pk = kwargs["pk"]
        campaign = Campaign.objects.get(pk=pk)
        if (campaign.creator.id != request.user.id): 
            return HttpResponseForbidden()
        return func(request, *args, **kwargs)
    return check_and_call
        
class CampaignOwnerMixin(object):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(CampaignOwnerMixin, cls).as_view(**initkwargs)
        return campaign_owner(view)

# Create your views here.
@login_required
def IndexView(request):
    nbTweets = Tweet.objects.all().count()
    nbRepliedTweets = TweetAction.objects.filter(action__type__exact="replied").count()
    
    return render(request, 'main/index.html', {'nbTweets': nbTweets, 'nbRepliedTweets': nbRepliedTweets})

class CampaignCreate(CreateWithInlinesView):
    model = Campaign
    inlines = [QueryFormSet]
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CreateWithInlinesView, self).dispatch(*args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        self.object = None
        
        if django.VERSION >= (1, 6) and self.fields is None and self.form_class is None:
            self.fields = '__all__'  # backward compatible with older versions

        form_class = self.get_form_class()
        form = self.get_form(form_class)

        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.creator = self.request.user
            form_validated = True
        else:
            form_validated = False

        inlines = self.construct_inlines()

        if all_valid(inlines) and form_validated:
            return self.forms_valid(form, inlines)
        return self.forms_invalid(form, inlines)
    
class CampaignUpdate(CampaignOwnerMixin, UpdateWithInlinesView):
    model = Campaign
    inlines = [QueryFormSetUpdate]
    template_name = 'main/campaign_form_update.html'
    
class CampaignView(CampaignOwnerMixin, DetailView):
    model = Campaign
  
@campaign_owner  
def CampaignSchedule(request, pk):
    campaign = get_object_or_404(Campaign, pk=pk)
    
    scheduler = django_rq.get_scheduler('default')
    job = scheduler.schedule(
        scheduled_time=datetime.datetime.now(),
        func=main.extras.TwitterBot.twitterBot,
        args=[campaign.pk],
        interval=3600,
        timeout=3600,
        repeat=None
    )

    campaign.jobId = job.id
    campaign.save()
    
    return redirect(campaign)

@campaign_owner
def CampaignUnschedule(request, pk):
    campaign = get_object_or_404(Campaign, pk=pk)
    
    scheduler = django_rq.get_scheduler('default')
    scheduler.cancel(campaign.jobId)
    
    campaign.jobId = None
    campaign.save()
    
    return redirect(campaign)
    
# def TweetActionReturn(request, tweet_id, action):
#     tweet = get_object_or_404(Tweet, tweet_id=tweet_id)
#     
#     tweetAction = tweet.tweet_actions.all()[0]
#     if (action == "clicked" and tweetAction.shortened_urls != None):
#         bitly = bitly_api.Connection(access_token = settings.BITLY_TOKEN)
#         if (bitly.link_clicks(tweetAction.getShortenedUrls()[0]) > 1):
#             tweetAction.clicked = True
#     elif (action == "created"):
#         tweetAction.prefrCreated = True
#     tweetAction.save()
#         
#     return JsonResponse({'status': 'ok'})
    

twitterautoreplybot/main/templates/main/campaign_detail.html
{% extends 'main/layout.html' %}
{% load i18n %}
{% load staticfiles %}

{% block page_title %}
    {{ campaign.name }}
{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    <li class="active"><i class="fa fa-feed"></i> {{ campaign.name }}</li>
{% endblock %}

{% block body %}
    {# Infos widget #}
    <div class="row">
        <div class="col-md-6">
            {% with campaign.tweet_actions.count as tweetsCount %}
                <div class="info-box bg-aqua">
                    <span class="info-box-icon"><i class="fa fa-twitter"></i></span>

                    {% if tweetsCount > 0 %}
                        <div class="info-box-content">
                            <span class="info-box-text">{% trans "Replies" %}</span>
                            <span class="info-box-number">{{ campaign.nbTweetsReplied }}</span>
                
                            {% widthratio campaign.nbTweetsReplied tweetsCount 100 as percentage %}
                            {% widthratio campaign.nbTweetsClicked campaign.nbTweetsReplied 100 as percentageClicked %}
                            <div class="progress">
                                <div class="progress-bar" style="width: {{ percentage }}%"></div>
                            </div>
                            <span class="progress-description"> 
                                {% blocktrans %}
                                    {{ percentage }}% of replies
                                {% endblocktrans %}
                                 - 
                                {% blocktrans %}
                                    {{ percentageClicked }}% of clicks
                                {% endblocktrans %}
                            </span>
                        </div>
                    {% else %}
                        <div class="info-box-content">
                            <span class="info-box-text">{% trans "No tweet processed yet" %}</span>
                            <span class="info-box-number">&nbsp;</span>
                
                            <div class="progress">
                                <div class="progress-bar" style="width: 0%"></div>
                            </div>
                            <span class="progress-description"> </span>
                        </div>
                    {% endif %}
                    <!-- /.info-box-content -->
                </div>
            {% endwith %}
        </div>
        <div class="col-md-6">
            <div class="info-box bg-{% if campaign.running %}green{% else %}yellow{% endif %}">
                <span class="info-box-icon"><i class="fa fa-cog {% if campaign.running %}fa-spin{% endif %}"></i></span>

                <div class="info-box-content">
                    <span class="info-box-text">{% trans "Status" %}</span>
                    <span class="info-box-number">
                        {% if campaign.running %}
                            {% trans "Running" %}
                        {% else %}
                            {% trans "Idle" %}
                        {% endif %}
                    </span>

                    <div class="progress">
                        <div class="progress-bar" style="width: 0%"></div>
                    </div>
                    <span class="progress-description">
                        {% if campaign.lastRun %}
                            {% blocktrans with lastRun=campaign.lastRun|date:"SHORT_DATETIME_FORMAT" %}
                                Last run: {{ lastRun }}
                            {% endblocktrans %}
                        {% else %}
                            {% trans "Never run" %}
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </div>
    
    {# Action buttons #}
    <div class="row" style="margin-bottom:10px">
        <div class="col-xs-6">
            <a href="{% url 'main:CampaignUpdate' pk=campaign.pk %}" class="btn btn-block btn-primary"><i class="fa fa-edit"></i> {% trans "Edit campaign" %}</a>
        </div>
        <div class="col-xs-6">
            {% if not campaign.jobId %}
                <a href="{% url 'main:CampaignSchedule' pk=campaign.pk %}" class="btn btn-block btn-success"><i class="fa fa-clock-o"></i> {% trans "Enable campaign" %}</a>
            {% else %}
                <a href="{% url 'main:CampaignUnschedule' pk=campaign.pk %}" class="btn btn-block btn-danger"><i class="fa fa-ban"></i> {% trans "Disable campaign" %}</a>
            {% endif %}
        </div>
    </div>
    
    {# Sentence recall #}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-warning">
                <div class="box-header with-border">
                    <h3 class="box-title">{% trans "Answer sentence" %}</h3>
                </div>
                <div class="box-body">
                    <pre>{{ campaign.answerSentence }}</pre>
                </div>
            </div>
        </div>
    </div>
    
    {# Queries #}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-warning">
                <div class="box-header with-border">
                    <h3 class="box-title">{% trans "Queries" %}</h3>
                </div>
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th style="width:75%">{% trans "Query" %}</th>
                                <th class="text-center">{% trans "Seen" %}</th>
                                <th class="text-center">{% trans "Replied" %}</th>
                                <th class="text-center">{% trans "Clicked" %}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for query in campaign.queries.all %}
                                <tr>
                                    <td>
                                        {{ query.query }}
                                    </td>
                                    <td class="text-center"><span class="badge">{{ query.nbTweetsSeen }}</span></td>
                                    <td class="text-center"><span class="badge">{{ query.nbTweetsReplied }}</span></td>
                                    <td class="text-center"><span class="badge">{% widthratio query.nbTweetsClicked query.nbTweetsReplied 100 %}%</span></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    
    {# Preview of last replied tweets #}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">{% trans "Last replied tweets" %}</h3>
                </div>
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>{% trans "Id." %}</th>
                                <th>{% trans "Message" %}</th>
                                <th>{% trans "Query" %}</th>
                                <th>{% trans "Clicked" %}</th>
                                <th class="text-center">{% trans "View" %}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for tweetDetails in campaign.getTweetDetails %}
                                <tr>
                                    <td>{{ tweetDetails.id }}</td>
                                    <td>{{ tweetDetails.message }}</td>
                                    <td>{{ tweetDetails.query.query }}</td>
                                    <td class="text-center"><i class="fa fa-{% if tweetDetails.clicked %}check{% else %}remove{% endif %}"></i></td>
                                    <td class="text-center"><a href="https://twitter.com/statuses/{{ tweetDetails.id }}" target="_blank" class="btn btn-xs btn-primary"><i class="fa fa-eye"></i> {% trans "View" %}</a></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

twitterautoreplybot/main/templates/main/campaign_form.html
{% extends 'main/layout.html' %}
{% load i18n %}
{% load bootstrap3 %}
{% load widget_tweaks %}
{% load staticfiles %}

{% block page_title %}
    {% trans "Create campaign" %}
{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
    {% block subbreadcrumb %}
        <li class="active"><i class="fa fa-feed"></i> {% trans "Create campaign" %}</li>
    {% endblock %}
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_field form.name size="large" show_label=False %}
                <div class="box box-info">
                    <div class="box-header with-border">
                        <h3 class="box-title">{% trans "Queries" %}</h3>
                    </div>         
                    <div class="box-body no-padding">                        
                        {% for form in inlines %}
                            {{ form.management_form }}
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th style="width:60%">{% trans "Query" %}</th>
                                        <th style="width:15%">{% trans "Magic word" %}</th>
                                        <th style="width:15%">{% trans "Nb. images req." %}</th>
                                        <th>{% trans "Delete" %}</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for query_set in form %}
                                        <tr id="inline-{{ form.prefix }}">
                                            {{ query_set.id }}
                                            <td>{{ query_set.query|attr:"class:form-control" }}</td>
                                            <td>{{ query_set.correspondingSentence|attr:"class:form-control" }}</td>
                                            <td>{{ query_set.requiredNumberOfImages|attr:"class:form-control" }}</td>
                                            <td class="text-center">{% if query_set.instance.pk %}{{ form.DELETE }}{% endif %}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        {% endfor %}
                    </div>
                </div>
                <div class="box box-success">
                    <div class="box-header with-border">
                        <h3 class="box-title">{% trans "Answer sentence" %}</h3>
                    </div>
                    <div class="box-body">
                        <div class="callout callout-info">
                            <h4>{% trans "Syntax" %}</h4>
                            <p>{% blocktrans %}To use the Twitter username, type :{% endblocktrans %}</p>
                            <pre>%twitterUsername%</pre>
                            <p>{% blocktrans %}To use the Tweet identifier, type :{% endblocktrans %}</p>
                            <pre>%tweetId%</pre>
                            <p>{% blocktrans %}To create a set of words picked at random, type :{% endblocktrans %}</p>
                            <pre>[word1|word2|word3]</pre>
                            <p>{% blocktrans %}To use the magic word from the query, type :{% endblocktrans %}</p>
                            <pre>%magicWord%</pre>
                        </div>
                        {% bootstrap_field form.answerSentence size="large" show_label=False %}
                    </div>
                </div>
                {% block submit_button %}
                    <button type="submit" class="btn btn-lg btn-block btn-primary">{% trans "Create campaign" %}</button>
                {% endblock %}
            </form>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ block.super }}
    <script src="{% static 'main/js/jquery.formset.min.js' %}"></script>
    <script type="text/javascript">
        {% for form in inlines %}
            $(function() {
                $("#inline-{{ form.prefix }}").formset({
                    prefix: "{{ form.prefix }}",
                    addText: "{% trans 'Add query' %}",
                    addCssClass: "add-row btn btn-primary",
                    deleteText: "<i class='fa fa-trash-o'></i>"
                })
            })
        {% endfor %}
    </script>
{% endblock %}

twitterautoreplybot/main/templates/main/layout.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% trans "Twitter Auto-Reply Bot" %}{% endblock %}</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    {% block stylesheets %}
        <link rel="stylesheet" href="{% static 'main/bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
        <link rel="stylesheet" href="{% static 'main/css/AdminLTE.min.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/awesome-bootstrap-checkbox.css' %}">
        <link rel="stylesheet" href="{% static 'main/css/skins/skin-yellow.min.css' %}">
    {% endblock %}
  </head>
  {% block all_content %}
  <body class="hold-transition skin-yellow sidebar-mini">
    
    <!-- Site wrapper -->
    <div class="wrapper">

      <header class="main-header">
        <!-- Logo -->
        <a href="../../index2.html" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><i class="fa fa-twitter"></i></span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><i class="fa fa-twitter"></i> <b>{% trans "Auto-Reply Bot" %}</b></span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- User Account: style can be found in dropdown.less -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="fa fa-user"></i> 
                    <span class="hidden-xs">{{ request.user.username }}</span>
                </a>
                <ul class="dropdown-menu">
                  <!-- User image -->
                  <li class="user-header">
                    <p>
                        {{ request.user.first_name }} {{ request.user.last_name }}
                    </p>
                  </li>
                  <!-- Menu Body -->
                  <li class="user-body">
                    <div class="col-xs-4 text-center">
                      <a href="#">Followers</a>
                    </div>
                    <div class="col-xs-4 text-center">
                      <a href="#">Sales</a>
                    </div>
                    <div class="col-xs-4 text-center">
                      <a href="#">Friends</a>
                    </div>
                  </li>
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-left">
                      <a href="#" class="btn btn-default btn-flat">{% trans "Profile" %}</a>
                    </div>
                    <div class="pull-right">
                      <a href="{% url 'django.contrib.auth.views.logout' %}" class="btn btn-default btn-flat">{% trans "Sign out" %}</a>
                    </div>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
      </header>

      <!-- =============================================== -->

        <!-- Left side column. contains the sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu">
                    {% url "main:IndexView" as mainIndexViewUrl %}
                    <li {% if request.get_full_path == mainIndexViewUrl %}class="active"{% endif %}>
                        <a href="{{ mainIndexViewUrl }}">
                            <i class="fa fa-dashboard"></i> <span>{% trans "Dashboard" %}</span>
                        </a>
                    </li>
                    {% url "main:CampaignCreate" as mainCampaignCreateUrl %}
                    <li class="treeview{% if request.get_full_path == mainCampaignCreateUrl or request.resolver_match.url_name == "CampaignView" or request.resolver_match.url_name == "CampaignUpdate" %} active{% endif %}">
                        <a href="#">
                        <i class="fa fa-feed"></i> <span>{% trans "Campaigns" %}</span> <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            <li {% if request.get_full_path == mainCampaignCreateUrl %}class="active"{% endif %}><a href="{{ mainCampaignCreateUrl }}"><i class="fa fa-plus-circle"></i> {% trans "New campaign" %}</a></li>
                            {% for campaign in request.user.campaigns.all %}
                                {% url "main:CampaignView" pk=campaign.pk as campaignViewUrl %}
                                {% url "main:CampaignUpdate" pk=campaign.pk as campaignUpdateUrl %}
                                <li {% if request.get_full_path == campaignViewUrl or request.get_full_path == campaignUpdateUrl %}class="active"{% endif %}><a href="{{ campaignViewUrl }}"><i class="fa fa-circle-o"></i> {{ campaign.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
            </section>
        <!-- /.sidebar -->
        </aside>

      <!-- =============================================== -->

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            {% block page_title %}{% endblock %}
            <small>{% block page_subtitle %}{% endblock %}</small>
          </h1>
          <ol class="breadcrumb">
            {% block breadcrumb %}
                <li><a href="{% url 'main:IndexView' %}"><i class="fa fa-dashboard"></i> {% trans "Dashboard" %}</a></li>
            {% endblock %}
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            {% block body %}{% endblock %}
        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

      <footer class="main-footer">
        {% trans "A Twitter auto-reply bot written in Python with a Django web interface" %} - <a href="https://github.com/frankie567/twitterautoreplybot" target="_blank">{% trans "Official GitHub repository" %}</a>
      </footer>
    </div><!-- ./wrapper -->
  </body>
    {% endblock %}

    {% block javascripts %}
        <script src="{% static 'main/plugins/jQuery/jQuery-2.1.4.min.js' %}"></script>
        <script src="{% static 'main/bootstrap/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'main/plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
        <script src="{% static 'main/plugins/fastclick/fastclick.min.js' %}"></script>
        <script src="{% static 'main/js/app.min.js' %}"></script>
        <script src="{% static 'main/js/main.js' %}"></script>
    {% endblock %}
</html>